
import { ThemeProvider } from '@/components/ThemeProvider'
import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import Bar from '@/components/Bar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'EZMonitor',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <Header/>
        {children}
      </ThemeProvider>
      </body>
    </html>
  )
}
